from __future__ import annotations

import importlib.util
import json
import subprocess
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from _helpers import REPO_ROOT, load_module

imagevector_scripts = load_module(
    "convert_image_to_imagevector",
    REPO_ROOT / "skills" / "kotlin-multiplatform-imagevector-generator" / "scripts" / "convert_image_to_imagevector.py",
)

_SAMPLE_SVG = """\
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <path fill="#1E3A5F" d="M10 10 L90 10 L90 90 L10 90 Z"/>
  <path fill="#E67E22" d="M50 20 C70 20 80 40 80 50 S70 80 50 80 Q30 80 25 50 T50 20 Z"/>
  <path fill="none" d="M0 0 L1 1"/>
</svg>
"""

class ImageVectorConverterTests(unittest.TestCase):
    def _convert(self, svg: str = _SAMPLE_SVG, **kw):
        with tempfile.TemporaryDirectory() as tmp:
            src = Path(tmp) / "logo.svg"
            src.write_text(svg, encoding="utf-8")
            return imagevector_scripts.convert(
                src, kw.get("name", "Logo"), kw.get("group_id", "com.example.app"),
                kw.get("viewport", 24.0), kw.get("color_mode", "literal"),
                kw.get("colors", 6), kw.get("max_nodes", 400), kw.get("package"),
            )

    def test_package_defaults_to_design_system_convention(self) -> None:
        kotlin, _ = self._convert(group_id="com.example.app")
        self.assertIn("package com.example.app.core.designsystem.icons", kotlin)

    def test_package_override_replaces_default_convention(self) -> None:
        # Real gap: core.designsystem.icons is the design-system skill's own module
        # layout, not universal — a project with a different structure needs to
        # override it without hand-editing the generated file afterward.
        kotlin, _ = self._convert(group_id="com.example.app", package="com.example.app.icons")
        self.assertIn("package com.example.app.icons", kotlin)
        self.assertNotIn("core.designsystem.icons", kotlin)

    def test_generates_header_and_property(self) -> None:
        kotlin, report = self._convert()
        self.assertIn("GENERATED by convert_image_to_imagevector", kotlin)
        self.assertIn("val Logo: ImageVector by lazy", kotlin)
        self.assertEqual(report["layers"], 2)  # fill=none path skipped

    def test_rescales_to_viewport(self) -> None:
        kotlin, _ = self._convert()
        # 10..90 in a 100-viewBox scaled to 24 → 2.4..21.6
        self.assertIn("moveTo(2.4f, 2.4f)", kotlin)
        self.assertIn("lineTo(21.6f, 21.6f)", kotlin)

    def test_smooth_and_quad_commands_emitted(self) -> None:
        kotlin, _ = self._convert()
        self.assertIn("curveTo(", kotlin)   # C and S both become curveTo
        self.assertIn("quadTo(", kotlin)    # Q and T both become quadTo

    def test_semantic_mode_merges_to_single_layer(self) -> None:
        kotlin, report = self._convert(color_mode="semantic")
        self.assertEqual(report["layers"], 1)
        self.assertIn("SolidColor(Color.Black)", kotlin)
        self.assertNotIn("0xFFE67E22", kotlin)

    def test_semantic_mode_fill_call_properly_closed(self) -> None:
        # Regression: the "color-agnostic" comment was once embedded inside the
        # path(fill = ...) argument list, so `//` commented out the closing `) {`
        # and broke every semantic-mode icon's generated Kotlin syntax.
        kotlin, _ = self._convert(color_mode="semantic")
        self.assertIn("SolidColor(Color.Black)) {", kotlin)
        self.assertNotIn("Color.Black)  //", kotlin)

    def test_node_budget_refuses_bloat(self) -> None:
        with self.assertRaises(SystemExit):
            self._convert(max_nodes=3)

    def test_arc_command_flattened_to_curves(self) -> None:
        # Real Heroicons paths are full of arcs (bell, user-circle, clock, etc.) —
        # these must convert to curveTo(...) calls, not raise.
        arc_svg = '<svg viewBox="0 0 10 10"><path fill="#000" d="M0 5 A5 5 0 0 1 10 5"/></svg>'
        kotlin, _ = self._convert(svg=arc_svg)
        self.assertIn("curveTo(", kotlin)
        self.assertNotIn("NaN", kotlin)

    def test_arc_semicircle_endpoint_is_accurate(self) -> None:
        # A semicircle of radius 5 from (0,5) to (10,5) (sweep=1) must end exactly
        # at the SVG endpoint regardless of how many cubic sub-segments it's split into.
        cmds = imagevector_scripts.parse_path("M0 5 A5 5 0 0 1 10 5")
        last = cmds[-1]
        self.assertEqual(last.op, "curve")
        self.assertAlmostEqual(last.args[-2], 10.0, places=3)
        self.assertAlmostEqual(last.args[-1], 5.0, places=3)

    def test_arc_packed_flags_parsed_correctly(self) -> None:
        # Arc flags are single 0/1 digits that may be packed with no separator before
        # the next number (e.g. "1110" = large-arc=1, sweep=1, x=10) — a classic SVG
        # arc-parsing gotcha that a naive float tokenizer misreads as one number "1110".
        cmds = imagevector_scripts.parse_path("M0 0A5 5 0 1110 0")
        curves = [c for c in cmds if c.op == "curve"]
        self.assertTrue(len(curves) >= 1)
        self.assertAlmostEqual(curves[-1].args[-2], 10.0, places=3)
        self.assertAlmostEqual(curves[-1].args[-1], 0.0, places=3)

    def test_zero_radius_arc_emits_line_not_curve(self) -> None:
        # rx=0 (or ry=0) is a degenerate ellipse — a straight line. Emitting a real
        # lineTo instead of a curveTo whose control points sit on that line is cheaper
        # against --max-nodes for the same visual result (matches picosvg's approach).
        cmds = imagevector_scripts.parse_path("M0 0A0 5 0 0 1 10 0")
        non_move = [c for c in cmds if c.op != "move"]
        self.assertEqual(len(non_move), 1)
        self.assertEqual(non_move[0].op, "line")
        self.assertAlmostEqual(non_move[0].args[0], 10.0, places=3)
        self.assertAlmostEqual(non_move[0].args[1], 0.0, places=3)

    def test_stroke_detection_positive(self) -> None:
        self.assertTrue(imagevector_scripts._svg_uses_strokes(
            '<svg fill="none" stroke="currentColor"><path d="M0 0 L10 10"/></svg>'
        ))

    def test_stroke_detection_ignores_none_and_transparent(self) -> None:
        self.assertFalse(imagevector_scripts._svg_uses_strokes(
            '<svg><path fill="#000" stroke="none" d="M0 0 L10 10"/></svg>'
        ))
        self.assertFalse(imagevector_scripts._svg_uses_strokes(
            '<svg><path fill="#000" stroke="transparent" d="M0 0 L10 10"/></svg>'
        ))

    def test_stroke_detection_negative_no_stroke_attr(self) -> None:
        self.assertFalse(imagevector_scripts._svg_uses_strokes(_SAMPLE_SVG))

    @unittest.skipUnless(
        importlib.util.find_spec("picosvg") is not None, "picosvg not installed"
    )
    def test_stroke_based_svg_converts_via_picosvg(self) -> None:
        # Real bug: this parser only ever reads `fill` — a stroke-based path's `d` is
        # a centerline, and filling it directly produces a solid blob with no error,
        # indistinguishable from a correct conversion. Stroke-only icon sets (Heroicons
        # Outline, Feather, Lucide, Tabler, Material Symbols Outlined) are common, not
        # an edge case. picosvg normalizes the stroke into a real filled outline first.
        stroke_svg = (
            '<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" '
            'stroke-width="1.5" stroke="currentColor">'
            '<path stroke-linecap="round" stroke-linejoin="round" '
            'd="M12 6v12m6-6H6"/></svg>'
        )
        kotlin, report = self._convert(svg=stroke_svg, color_mode="semantic")
        self.assertGreater(report["nodes"], 0)
        self.assertTrue(
            "curveTo(" in kotlin or "lineTo(" in kotlin or "quadTo(" in kotlin
        )

    def test_near_quarter_circle_roundoff_uses_one_segment(self) -> None:
        # This specific radius/start-angle combination is a verified reproduction of
        # a real case where the endpoint-to-center parameterization's acos/atan2 chain
        # computes dtheta as 1.570796326794897 instead of exactly math.pi/2
        # (1.5707963267948966) — a 90-degree arc, off by ~4e-16. Without the
        # picosvg-matching epsilon in the segment-count ceil(), that sliver pushes the
        # arc from 1 segment to 2 unnecessary ones.
        segments = imagevector_scripts._arc_to_cubics(
            -7.580376014150292, 0.2294545431208891,
            7.58384796150766, 7.58384796150766, 0,
            False, True,
            -0.2294545431208862, -7.580376014150292,
        )
        self.assertEqual(len(segments), 1)

    def test_relative_commands_become_absolute(self) -> None:
        rel_svg = '<svg viewBox="0 0 24 24"><path fill="#000" d="m2 2 l4 0 v4 h-4 z"/></svg>'
        kotlin, _ = self._convert(svg=rel_svg)
        self.assertIn("moveTo(2f, 2f)", kotlin)
        self.assertIn("lineTo(6f, 2f)", kotlin)
        self.assertIn("lineTo(6f, 6f)", kotlin)
        self.assertIn("lineTo(2f, 6f)", kotlin)


if __name__ == "__main__":
    unittest.main()
